from .start import start_router
from .exercise import add_task_router
from .competition import add_competition_router
from .tasks import my_tasks_router
from .deadlines import missed_deadlines_router
from .heal import heal_router
from .leaderboard import leaderboard_router
from .profiles import my_profile_router
from .marking_students import mark_students_router