"""add root me nickname

Revision ID: 9f1e05db874e
Revises: cbb56810f48d
Create Date: 2024-11-30 18:13:18.324480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f1e05db874e"
down_revision: Union[str, None] = "cbb56810f48d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("root_me_nickname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "root_me_nickname")
    # ### end Alembic commands ###
