"""Add telegram id to User

Revision ID: a823942ffa16
Revises: b0d97aa866a4
Create Date: 2025-03-15 17:47:00.489915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a823942ffa16'
down_revision: Union[str, None] = 'b0d97aa866a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
